version: "3.7"

services:
  astro:
    container_name: astro
    build:
      context: ./site
      target: dev-test
    restart: always
    ports:
      - 4321:4321
      - 4322:4322
    volumes:
      - '.:/useable'
